#!/bin/bash
function volume() {
    OUTPUT=$(pactl list sinks | grep 'Volume:' | head -n 1 | awk '{print $5}' | sed 's/%//g')
    echo "$OUTPUT"
}

function network() {
    OUTPUT=$(ip addr show | grep enp6s0 | grep -oP '(?<=inet\s)\d+(\.\d+){3}' | head -n 1)
    echo "$OUTPUT"
}

function workspaces() {
    output_array=("[]")
    for i in {1..10}
    do
        active_workspaces="$(hyprctl workspaces -j | jq '.[] | .id')"
        active_workspace="$(hyprctl activeworkspace | head -n 1 | awk '{print $3}')"
        if [[ $i == $active_workspace ]]; then
            output_array+=("[$i, \"active\"]")
            continue
        fi
        for aws in $active_workspaces; do
            found=false
            if [[ $aws == $i ]]; then
                output_array+=("[$i, \"inactive\"]")
                found=true
                break
            fi
        done
        if ! $found; then
            output_array+=("[$i, \"empty\"]")
        fi
    done
    printf -v output "%s, " "${output_array[@]}"
    output="${output%, }"
    echo "[$output]"
    socat -u UNIX-CONNECT:/tmp/hypr/"$HYPRLAND_INSTANCE_SIGNATURE"/.socket2.sock - | while read -r; do
        workspaces
    done
}

function cpu() {
    echo "$(awk '/^cpu / {print ($2+$4)*100/($2+$4+$5)}' /proc/stat)"
}

function disk() {
    echo "$(df -h $1 | awk 'NR==2{print $(NF-1)}')"
}

function music() {
    playerctl --follow metadata  | while read -r; do
        echo "$(playerctl metadata --format '{{ artist }} - {{ title }}' | cut -c -45)"
    done
}


if [ "$1" == "volume" ]; then
    volume
elif [ "$1" == "network" ]; then
    network
elif [ "$1" == "workspaces" ]; then
    workspaces
elif [ "$1" == "cpu" ]; then
    cpu
elif [ "$1" == "disk" ]; then
    disk $2
elif [ "$1" == "music" ]; then
    music
else
    echo "Invalid parameter"
fi